name: russian101
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  assets:
   - assets/lesson1/1.m4a
   - assets/lesson1/1.png
   - assets/lesson1/10.m4a
   - assets/lesson1/10.png
   - assets/lesson1/11.m4a
   - assets/lesson1/11.png
   - assets/lesson1/12.m4a
   - assets/lesson1/12.png
   - assets/lesson1/13.m4a
   - assets/lesson1/13.png
   - assets/lesson1/14.m4a
   - assets/lesson1/14.png
   - assets/lesson1/15.m4a
   - assets/lesson1/15.png
   - assets/lesson1/16.m4a
   - assets/lesson1/16.png
   - assets/lesson1/17.m4a
   - assets/lesson1/17.png
   - assets/lesson1/18.m4a
   - assets/lesson1/18.png
   - assets/lesson1/19.m4a
   - assets/lesson1/19.png
   - assets/lesson1/2.m4a
   - assets/lesson1/2.png
   - assets/lesson1/20.m4a
   - assets/lesson1/20.png
   - assets/lesson1/21.m4a
   - assets/lesson1/21.png
   - assets/lesson1/22.m4a
   - assets/lesson1/22.png
   - assets/lesson1/23.m4a
   - assets/lesson1/23.png
   - assets/lesson1/24.m4a
   - assets/lesson1/24.png
   - assets/lesson1/25.m4a
   - assets/lesson1/25.png
   - assets/lesson1/26.m4a
   - assets/lesson1/26.png
   - assets/lesson1/27.m4a
   - assets/lesson1/27.png
   - assets/lesson1/28.m4a
   - assets/lesson1/28.png
   - assets/lesson1/29.m4a
   - assets/lesson1/29.png
   - assets/lesson1/3.m4a
   - assets/lesson1/3.png
   - assets/lesson1/30.m4a
   - assets/lesson1/30.png
   - assets/lesson1/31.m4a
   - assets/lesson1/31.png
   - assets/lesson1/32.m4a
   - assets/lesson1/32.png
   - assets/lesson1/33.m4a
   - assets/lesson1/33.png
   - assets/lesson1/34.m4a
   - assets/lesson1/34.png
   - assets/lesson1/35.m4a
   - assets/lesson1/35.png
   - assets/lesson1/4.m4a
   - assets/lesson1/4.png
   - assets/lesson1/5.m4a
   - assets/lesson1/5.png
   - assets/lesson1/6.m4a
   - assets/lesson1/6.png
   - assets/lesson1/7.m4a
   - assets/lesson1/7.png
   - assets/lesson1/8.m4a
   - assets/lesson1/8.png
   - assets/lesson1/9.m4a
   - assets/lesson1/9.png
   - assets/lesson10/1.m4a
   - assets/lesson10/1.png
   - assets/lesson10/10.m4a
   - assets/lesson10/10.png
   - assets/lesson10/11.m4a
   - assets/lesson10/11.png
   - assets/lesson10/12.m4a
   - assets/lesson10/12.png
   - assets/lesson10/13.m4a
   - assets/lesson10/13.png
   - assets/lesson10/14.m4a
   - assets/lesson10/14.png
   - assets/lesson10/15.m4a
   - assets/lesson10/15.png
   - assets/lesson10/16.m4a
   - assets/lesson10/16.png
   - assets/lesson10/17.m4a
   - assets/lesson10/17.png
   - assets/lesson10/18.m4a
   - assets/lesson10/18.png
   - assets/lesson10/19.m4a
   - assets/lesson10/19.png
   - assets/lesson10/2.m4a
   - assets/lesson10/2.png
   - assets/lesson10/20.m4a
   - assets/lesson10/20.png
   - assets/lesson10/21.m4a
   - assets/lesson10/21.png
   - assets/lesson10/22.m4a
   - assets/lesson10/22.png
   - assets/lesson10/23.m4a
   - assets/lesson10/23.png
   - assets/lesson10/24.m4a
   - assets/lesson10/24.png
   - assets/lesson10/3.m4a
   - assets/lesson10/3.png
   - assets/lesson10/4.m4a
   - assets/lesson10/4.png
   - assets/lesson10/5.m4a
   - assets/lesson10/5.png
   - assets/lesson10/6.m4a
   - assets/lesson10/6.png
   - assets/lesson10/7.m4a
   - assets/lesson10/7.png
   - assets/lesson10/8.m4a
   - assets/lesson10/8.png
   - assets/lesson10/9.m4a
   - assets/lesson10/9.png
   - assets/lesson2/1.m4a
   - assets/lesson2/1.png
   - assets/lesson2/2.m4a
   - assets/lesson2/2.png
   - assets/lesson2/3.m4a
   - assets/lesson2/3.png
   - assets/lesson2/4.m4a
   - assets/lesson2/4.png
   - assets/lesson2/5.m4a
   - assets/lesson2/5.png
   - assets/lesson2/6.m4a
   - assets/lesson2/6.png
   - assets/lesson2/7.m4a
   - assets/lesson2/7.png
   - assets/lesson2/8.m4a
   - assets/lesson2/8.png
   - assets/lesson2/9.m4a
   - assets/lesson2/9.png
   - assets/lesson3/1.m4a
   - assets/lesson3/1.png
   - assets/lesson3/2.m4a
   - assets/lesson3/2.png
   - assets/lesson3/3.m4a
   - assets/lesson3/3.png
   - assets/lesson3/4.m4a
   - assets/lesson3/4.png
   - assets/lesson3/5.m4a
   - assets/lesson3/5.png
   - assets/lesson3/6.m4a
   - assets/lesson3/6.png
   - assets/lesson3/7.m4a
   - assets/lesson3/7.png
   - assets/lesson3/8.m4a
   - assets/lesson3/8.png
   - assets/lesson4/1.m4a
   - assets/lesson4/1.png
   - assets/lesson4/10.m4a
   - assets/lesson4/10.png
   - assets/lesson4/11.m4a
   - assets/lesson4/11.png
   - assets/lesson4/12.m4a
   - assets/lesson4/12.png
   - assets/lesson4/13.m4a
   - assets/lesson4/13.png
   - assets/lesson4/2.m4a
   - assets/lesson4/2.png
   - assets/lesson4/3.m4a
   - assets/lesson4/3.png
   - assets/lesson4/4.m4a
   - assets/lesson4/4.png
   - assets/lesson4/5.m4a
   - assets/lesson4/5.png
   - assets/lesson4/6.m4a
   - assets/lesson4/6.png
   - assets/lesson4/7.m4a
   - assets/lesson4/7.png
   - assets/lesson4/8.m4a
   - assets/lesson4/8.png
   - assets/lesson4/9.m4a
   - assets/lesson4/9.png
   - assets/lesson5/1.m4a
   - assets/lesson5/1.png
   - assets/lesson5/2.m4a
   - assets/lesson5/2.png
   - assets/lesson5/3.m4a
   - assets/lesson5/3.png
   - assets/lesson5/4.m4a
   - assets/lesson5/4.png
   - assets/lesson5/5.m4a
   - assets/lesson5/5.png
   - assets/lesson5/6.m4a
   - assets/lesson5/6.png
   - assets/lesson5/7.m4a
   - assets/lesson5/7.png
   - assets/lesson5/8.m4a
   - assets/lesson5/8.png
   - assets/lesson6/1.m4a
   - assets/lesson6/1.png
   - assets/lesson6/10.m4a
   - assets/lesson6/10.png
   - assets/lesson6/11.m4a
   - assets/lesson6/11.png
   - assets/lesson6/12.m4a
   - assets/lesson6/12.png
   - assets/lesson6/13.m4a
   - assets/lesson6/13.png
   - assets/lesson6/14.m4a
   - assets/lesson6/14.png
   - assets/lesson6/15.m4a
   - assets/lesson6/15.png
   - assets/lesson6/16.m4a
   - assets/lesson6/16.png
   - assets/lesson6/17.m4a
   - assets/lesson6/17.png
   - assets/lesson6/18.m4a
   - assets/lesson6/18.png
   - assets/lesson6/19.m4a
   - assets/lesson6/19.png
   - assets/lesson6/2.m4a
   - assets/lesson6/2.png
   - assets/lesson6/20.m4a
   - assets/lesson6/20.png
   - assets/lesson6/21.m4a
   - assets/lesson6/21.png
   - assets/lesson6/22.m4a
   - assets/lesson6/22.png
   - assets/lesson6/23.m4a
   - assets/lesson6/23.png
   - assets/lesson6/24.m4a
   - assets/lesson6/24.png
   - assets/lesson6/25.m4a
   - assets/lesson6/25.png
   - assets/lesson6/26.m4a
   - assets/lesson6/26.png
   - assets/lesson6/27.m4a
   - assets/lesson6/27.png
   - assets/lesson6/3.m4a
   - assets/lesson6/3.png
   - assets/lesson6/4.m4a
   - assets/lesson6/4.png
   - assets/lesson6/5.m4a
   - assets/lesson6/5.png
   - assets/lesson6/6.m4a
   - assets/lesson6/6.png
   - assets/lesson6/7.m4a
   - assets/lesson6/7.png
   - assets/lesson6/8.m4a
   - assets/lesson6/8.png
   - assets/lesson6/9.m4a
   - assets/lesson6/9.png
   - assets/lesson7/1.m4a
   - assets/lesson7/1.png
   - assets/lesson7/10.m4a
   - assets/lesson7/10.png
   - assets/lesson7/11.m4a
   - assets/lesson7/11.png
   - assets/lesson7/12.m4a
   - assets/lesson7/12.png
   - assets/lesson7/13.m4a
   - assets/lesson7/13.png
   - assets/lesson7/14.m4a
   - assets/lesson7/14.png
   - assets/lesson7/15.m4a
   - assets/lesson7/15.png
   - assets/lesson7/16.m4a
   - assets/lesson7/16.png
   - assets/lesson7/17.m4a
   - assets/lesson7/17.png
   - assets/lesson7/18.m4a
   - assets/lesson7/18.png
   - assets/lesson7/19.m4a
   - assets/lesson7/19.png
   - assets/lesson7/2.m4a
   - assets/lesson7/2.png
   - assets/lesson7/20.m4a
   - assets/lesson7/20.png
   - assets/lesson7/21.m4a
   - assets/lesson7/21.png
   - assets/lesson7/22.m4a
   - assets/lesson7/22.png
   - assets/lesson7/23.m4a
   - assets/lesson7/23.png
   - assets/lesson7/3.m4a
   - assets/lesson7/3.png
   - assets/lesson7/4.m4a
   - assets/lesson7/4.png
   - assets/lesson7/5.m4a
   - assets/lesson7/5.png
   - assets/lesson7/6.m4a
   - assets/lesson7/6.png
   - assets/lesson7/7.m4a
   - assets/lesson7/7.png
   - assets/lesson7/8.m4a
   - assets/lesson7/8.png
   - assets/lesson7/9.m4a
   - assets/lesson7/9.png
   - assets/lesson8/1.m4a
   - assets/lesson8/1.png
   - assets/lesson8/10.m4a
   - assets/lesson8/10.png
   - assets/lesson8/11.m4a
   - assets/lesson8/11.png
   - assets/lesson8/12.m4a
   - assets/lesson8/12.png
   - assets/lesson8/13.m4a
   - assets/lesson8/13.png
   - assets/lesson8/14.m4a
   - assets/lesson8/14.png
   - assets/lesson8/15.m4a
   - assets/lesson8/15.png
   - assets/lesson8/16.m4a
   - assets/lesson8/16.png
   - assets/lesson8/17.m4a
   - assets/lesson8/17.png
   - assets/lesson8/18.m4a
   - assets/lesson8/18.png
   - assets/lesson8/2.m4a
   - assets/lesson8/2.png
   - assets/lesson8/3.m4a
   - assets/lesson8/3.png
   - assets/lesson8/4.m4a
   - assets/lesson8/4.png
   - assets/lesson8/5.m4a
   - assets/lesson8/5.png
   - assets/lesson8/6.m4a
   - assets/lesson8/6.png
   - assets/lesson8/7.m4a
   - assets/lesson8/7.png
   - assets/lesson8/8.m4a
   - assets/lesson8/8.png
   - assets/lesson8/9.m4a
   - assets/lesson8/9.png
   - assets/lesson9/1.m4a
   - assets/lesson9/1.png
   - assets/lesson9/10.m4a
   - assets/lesson9/10.png
   - assets/lesson9/11.m4a
   - assets/lesson9/11.png
   - assets/lesson9/12.m4a
   - assets/lesson9/12.png
   - assets/lesson9/13.m4a
   - assets/lesson9/13.png
   - assets/lesson9/14.m4a
   - assets/lesson9/14.png
   - assets/lesson9/15.m4a
   - assets/lesson9/15.png
   - assets/lesson9/16.m4a
   - assets/lesson9/16.png
   - assets/lesson9/17.m4a
   - assets/lesson9/17.png
   - assets/lesson9/18.m4a
   - assets/lesson9/18.png
   - assets/lesson9/2.m4a
   - assets/lesson9/2.png
   - assets/lesson9/3.m4a
   - assets/lesson9/3.png
   - assets/lesson9/4.m4a
   - assets/lesson9/4.png
   - assets/lesson9/5.m4a
   - assets/lesson9/5.png
   - assets/lesson9/6.m4a
   - assets/lesson9/6.png
   - assets/lesson9/7.m4a
   - assets/lesson9/7.png
   - assets/lesson9/8.m4a
   - assets/lesson9/8.png
   - assets/lesson9/9.m4a
   - assets/lesson9/9.png

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
